spring:
  application:
    name: spring-7-rest-mvc
  # Desabilita Flyway em H2
  flyway:
    enabled: false
#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql

logging:
  level:
    web: TRACE
    guru.springframework: DEBUG