spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root # Secret is in plain text.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
