spring:
  application:
    name: spring-7-rest-mvc
#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql
logging:
  level:
    guru.springframework: debug